name: app_controller
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.0.0

dependencies:
  core:
    path: ../../core
  core_tdlib_api:
    path: ../../core_tdlib_api
  device_info_plus: 3.2.2
  path_provider: 2.0.9
  rxdart: 0.27.3
  td_api:
    path: ../../td/td_api

dev_dependencies:
  build_runner: 2.3.3
  dependency_validator: 3.2.0
  mockito: 5.4.0
  test: 1.24.0
  test_utils:
    path: ../../test_utils
  tg_lint_rules:
    path: ../../tg_lint_rules