name: core_presentation
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.0.0

dependencies:
  core:
    path: ../core
  core_utils:
    path: ../core_utils
  freezed_annotation: 2.2.0
  shared_models:
    path: ../shared/models
  td_api:
    path: ../td/td_api

dev_dependencies:
  build_runner: 2.3.3
  dependency_validator: 3.2.0
  freezed: 2.2.1
  tg_lint_rules:
    path: ../tg_lint_rules