name: link_resolver_impl
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  link_resolver_api:
    path: ../link_resolver_api

dev_dependencies:
  dependency_validator: 3.2.0
  test: 1.24.0
  tg_lint_rules:
    path: ../../../tg_lint_rules