name: core_arch
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  async: 2.11.0
  async_utils:
    path: ../async_utils

dev_dependencies:
  dependency_validator: 3.2.0
  tg_lint_rules:
    path: ../tg_lint_rules