builders:
  factory_widget_generator:
    import: "package:factory_widget_generator/builder.dart"
    builder_factories: ["fwg"]
    build_extensions: { ".dart": [".fwg.dart"] }
    auto_apply: dependents
    build_to: source