name: chat_list_ui_kit
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.0.0

dependencies:
  badges: 2.0.2
  chat_list_theme:
    path: ../../../feature/chat_list/chat_list_theme
  flutter:
    sdk: flutter
  flutter_svg: 1.0.3
  tg_theme:
    path: ../../../feature/theme/tg_theme

dev_dependencies:
  dependency_validator: 3.2.0
  tg_lint_rules:
    path: ../../../tg_lint_rules