name: link_resolver_api
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed_annotation: 2.2.0

dev_dependencies:
  build_runner: 2.3.3
  dependency_validator: 3.2.0
  freezed: 2.2.1
  tg_lint_rules:
    path: ../../../tg_lint_rules