name: coreui
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.0.0

dependencies:
  core_presentation:
    path: ../core_presentation
# TODO: do not depend on this module
  core_tdlib_api:
    path: ../core_tdlib_api
  feature_file_api:
    path: ../feature/feature_file_api
  flutter:
    sdk: flutter
  freezed_annotation: 2.2.0
  fwg_annotation:
    path: ../factory_widget_generator/annotation
  lottie: 1.3.0
  rxdart: 0.27.3
  shared_models:
    path: ../shared/models
  td_api:
    path: ../td/td_api

dev_dependencies:
  build_runner: 2.3.3
  dependency_validator: 3.2.0
  factory_widget_generator:
    path: ../factory_widget_generator/generator
  freezed: 2.2.1
  tg_lint_rules:
    path: ../tg_lint_rules

flutter:
  assets:
    - assets/icon/