name: feature_profile_impl
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.0.0

dependencies:
  chat_info:
    path: ../../chat/chat_info
  core_arch:
    path: ../../../core_arch
  core_arch_flutter:
    path: ../../../core_arch_flutter
  core_tdlib_api:
    path: ../../../core_tdlib_api
  coreui:
    path: ../../../coreui
  dmg_annotation:
    path: ../../../dependencies_module_generator/dmg_annotation
  feature_chat_header_info_api:
    path: ../../feature_chat_header_info_api
  feature_profile_api:
    path: ../feature_profile_api
  feature_shared_media_api:
    path: ../../feature_shared_media_api
  flutter:
    sdk: flutter
  freezed_annotation: 2.2.0
  jugger: 3.0.0
  localization_api:
    path: ../../../localization_api
  rxdart: 0.27.3
  scope_generator_annotation:
    path: ../../../scope_generator/scope_generator_annotation
  td_api:
    path: ../../../td/td_api
  tuple: 2.0.0
  user_info:
    path: ../../user/user_info

dev_dependencies:
  build_runner: 2.3.3
  dependencies_module_generator:
    path: ../../../dependencies_module_generator/generator
  dependency_validator: 3.2.0
  freezed: 2.2.1
  jugger_generator: 3.1.1
  scope_generator:
    path: ../../../scope_generator/generator
  tg_lint_rules:
    path: ../../../tg_lint_rules