name: feature_wallpapers_impl
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.0.0

dependencies:
  async: 2.11.0
  async_utils:
    path: ../../async_utils
  chat_kit:
    path: ../../feature/chat/chat_kit
  core_arch:
    path: ../../core_arch
  core_arch_flutter:
    path: ../../core_arch_flutter
  core_tdlib_api:
    path: ../../core_tdlib_api
  core_utils:
    path: ../../core_utils
  coreui:
    path: ../../coreui
  feature_file_api:
    path: ../feature_file_api
  feature_wallpapers_api:
    path: ../feature_wallpapers_api
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  flutter_staggered_grid_view: 0.4.0
  freezed_annotation: 2.2.0
  localization_api:
    path: ../../localization_api
  provider: 6.0.2
  rxdart: 0.27.3
  shared_models:
    path: ../../shared/models
  td_api:
    path: ../../td/td_api
  tile:
    path: ../../tile

dev_dependencies:
  build_runner: 2.3.3
  dependency_validator: 3.2.0
  freezed: 2.2.1
  tg_lint_rules:
    path: ../../tg_lint_rules