name: feature_contacts_impl
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.0.0

dependencies:
  chat_navigation_api:
    path: ../../../chat/chat_navigation_api
  core_arch:
    path: ../../../../core_arch
  core_arch_flutter:
    path: ../../../../core_arch_flutter
  core_tdlib_api:
    path: ../../../../core_tdlib_api
  core_ui_jugger:
    path: ../../../../core_ui_jugger
  coreui:
    path: ../../../../coreui
  dmg_annotation:
    path: ../../../../dependencies_module_generator/dmg_annotation
  feature_contacts_api:
    path: ../feature_contacts_api
  flutter:
    sdk: flutter
  jugger: 3.0.0
  localization_api:
    path: ../../../../localization_api
  scope_generator_annotation:
    path: ../../../../scope_generator/scope_generator_annotation

dev_dependencies:
  build_runner: 2.3.3
  dependencies_module_generator:
    path: ../../../../dependencies_module_generator/generator
  dependency_validator: 3.2.0
  jugger_generator: 3.1.1
  scope_generator:
    path: ../../../../scope_generator/generator
  tg_lint_rules:
    path: ../../../../tg_lint_rules