name: rich_text_format_flutter
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.0.0

dependencies:
  emoji_ui_kit:
    path: ../../ui/emoji_ui_kit
  flutter:
    sdk: flutter
  rich_text_format:
    path: ../rich_text_format

dev_dependencies:
  dependency_validator: 3.2.0
  tg_lint_rules:
    path: ../../tg_lint_rules