name: split_view
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.0.0

dependencies:
  collection: 1.18.0
  flutter:
    sdk: flutter

dev_dependencies:
  dependency_validator: 3.2.0
  flutter_test:
    sdk: flutter
  tg_lint_rules:
    path: ../tg_lint_rules