name: auth_manager_impl
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auth_manager_api:
    path: ../auth_manager_api
  core_tdlib_api:
    path: ../../../core_tdlib_api
  td_api:
    path: ../../../td/td_api

dev_dependencies:
  dependency_validator: 3.2.0
  tg_lint_rules:
    path: ../../../tg_lint_rules